### ISSUE TITLE
Unable to set offensive target 

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#48]
I was standing near another avatar (about 9m away) and tried to set the offensive target.  The popup told me there was nobody in range.

https://gyazo.com/54c4f9da48f41a54e246d423ab5703af

Note: I've also tried to do this during a battle where certain people just didn't appear on the target popup.

**Comment by ezebongiovi** [comment]
@MorphLupindo In order to add a target you must be looking at the target directly with your avatar. If you are standing a side, looking to a different direction, it will not appear on your target selection. I'm closing this issue since I cannot replicate  it on current version. Please feel free to re-open it if you are still having this issue
