### ISSUE TITLE
Fae silence skill has bigger area range than vampire ignite skill

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#94]
so, the vampire can't skill the fae, but she can skill the vampire.  I suggest limiting the range of silence to 10m and expanding ignite to 12-15m.  If the fae wants to silence, she's going to have to risk getting within range of her target.

**Comment by ezebongiovi** [comment]
We agree that this skill and many others have balancing issues. We don't consider those as METER bugs. At this very early stage of NCS we are learning about it's performance and how to balance it. So we will be doing changes that affect balance for quite a long time. Probably doing and un-doing changes to test in the field.

I cannot reward balancing reports since it's not a bug and it's something that will change tons of times along time until we find the **balance point**. I really appreciate this report. We've made the changes **we consider would help balancing** but we cannot guaranty those changes will remain until we understand the impact of it.

Again, thank you for your report. Specially you, that have been helping a lot during the testing and bug finding process. 🥇
